# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "56374e85fd6e6eea470f0523c274c13c"
name = "Claude Chat Bot"
application_url = "https://srv1574024.hstgr.cloud"
embedded = true
handle = "claude-chat-bot"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/api/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "products/create", "products/update", "products/delete" ]
  uri = "/api/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "collections/update" ]
  uri = "/api/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "shop/update" ]
  uri = "/api/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "unauthenticated_read_product_listings,read_products,read_orders,read_customers,read_content,read_themes,read_locales,read_shipping,read_markets,read_legal_policies,read_online_store_pages,customer_read_customers,customer_read_orders,customer_read_store_credit_account_transactions,customer_read_store_credit_accounts"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[pos]
embedded = false

[customer_authentication]
redirect_uris = [ "https://shop-chat-agent.com/callback" ]
